config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#landing_page'
  resources :suggestions, only: [:create]
  resources :profiles, only: [:edit, :show, :update, :index]
  resources :join_requests, only: [:destroy] do
    delete '/enroll', to: 'join_requests#enroll'
  end
  namespace :member do
    resources :groups, only: [:show, :index] do
      resources :messages, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :enrollments, only: [:destroy]
  resources :groups do
    resources :enrollments, only: [:create]
    resources :join_requests, only: [:create]
  end
  resources :user_messages, only: [:index]
  resources :users do
    resources :user_messages, only: [:new, :create, :destroy]
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

  after_create :send_welcome_email

  def country_name
    return '' unless country.present?
    country_fullname = ISO3166::Country[country]
    country_fullname.translations[I18n.locale.to_s] || country_fullname.name
  end

  def send_welcome_email
    NotificationMailer.delay.welcome_user(user.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_authorized_for_action, only: [:edit, :update]
  def index
    @profiles = Profile.all
  end

  def show
    @profile = user_of_profile.profile
    @user_message = UserMessage.new
    @receipient = params[:id]
    if @profile.time_zone.present?
      timezone = ActiveSupport::TimeZone[@profile.time_zone]
      @offset = timezone.formatted_offset
    end
  end

  def edit
    @profile = user_of_profile.profile
  end

  def update
    user_of_profile.profile.update_attributes(profile_params)
    redirect_to profile_path(user_of_profile)
  end

  private

  def user_of_profile
    @user ||= User.find(params[:id])
  end

  def require_authorized_for_action
    return render_not_found(:unauthorized) unless current_user == user_of_profile
  end

  def profile_params
    params.require(:profile).permit(:user_name, :remote_ok?, :avatar, :description, :country, :time_zone)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class='col-xs-10 col-xs-offset-1'>
  <h1>Update Profile</h1>
  <br/>
  <% if @profile.avatar.present? %>
    <%= image_tag @profile.avatar, class: 'profile-image' %>
  <% else %>
    <%= image_tag 'profile_image_placeholder.png', class: 'profile-image' %>
  <% end %>
  <br/><br/>
  <%= simple_form_for @profile, url: profile_path(current_user) do |f| %>
    <%= f.input :avatar %>
    <br/>
    <%= f.input :user_name %>
    <br/>
    <%= f.input :country, priority: ['United States', 'Australia', 'Singapore'] %>  
    <br/>
    <%= f.input :time_zone, priority: /Australia|US|Singapore/ %>
    <br/>    
    <%= f.input :description%>
    <br/>
    <%= f.input :remote_ok?%>
    <br/>
    <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/profiles/index.html.erb
<div class='col-xs-12 col-sm-10 col-sm-offset-1'>
  <div class='user-profiles-inner'>
    <% @profiles.each do |profile| %>
      <div class='user-profile-card'>
        <%= link_to profile_path(profile.user), class: 'profile-card-link' do %>
        <div class='user-profile-card_heading'>
          <% if profile.avatar.present? %>
            <%= image_tag profile.avatar, class: 'user-profile-card_image' %>
          <% else %>
            <%= image_tag 'profile_image_placeholder.png', class: 'user-profile-card_image' %>
          <% end %>       
          <h4 class='user-profile-card_name'><%= profile.user_name %></h4>  
          <% end %>
        </div>
        <%= link_to profile_path(profile.user), class: 'profile-card-link' do %>
        <div class='user-profile-card_details'>
          <div class='profile-card-details_country'>
            <p class='profile-field'>Country</p>
            <p class='profile-value'><%= profile.country_name %></p>
          </div>
          <div class='profile-card-details_timezone clear'>
            <p class='profile-field'>Time Zone</p>
            <p class='profile-value'><%= profile.time_zone %></p>
          </div>
          <div class='profile-card-details_remote clear'>
            <p class='profile-field'>Work Remotely?</p>
            <p class='profile-value'>
              <% if profile.remote_ok? %>
                Remote
              <% else %>
                Local Only
              <% end %>
            </p>
          </div>
          <div class='profile-card-details_groups clear'>
            <p class='profile-field'>No. of Groups</p>
            <p class='profile-value'><%= profile.user.enrolled_groups.count %></p>            
          </div>
          <div class='profile-card-details_description clear'>
            <%= profile.description %>
          </div>          
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class='col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12'>
  <div class='current-profile-contents'>
    <% if @profile.avatar.present? %>
      <%= image_tag @profile.avatar, class: 'profile-image' %>
    <% else %>
      <%= image_tag 'profile_image_placeholder.png', class: 'profile-image' %>
    <% end %>
    <br/>
    <div class='user-profile'>
      <h3>Hi, I am <span class='user-detail'><%= @profile.user_name %></span>, I live in <span class='user-detail'><%= @profile.country_name %></span>. My time zone is currently <span class='user-detail'>(GMT<%= @offset %>) <%= @profile.time_zone %></span></h3>
      <% if @profile.remote_ok? %>
        <p>I am happy learn remotely!</p>
      <% else %>
        <p>I am looking to join local groups!</p>
      <% end %>
      <p><%= @profile.description %></p>
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createMessageModal">
        <%= "Message #{@profile.user_name}" %>
      </button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="createMessageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Message <%= @profile.user_name %></h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for @user_message, url: user_user_messages_path(@profile.user), method: :post do |f| %>
              <%= f.input :message_title %>
              <%= f.input :message_description, as: :ckeditor, input_html: { ckeditor: {toolbar: 'projects'}} %>  
          </div>
          <div class="modal-footer">            
              <%= f.submit 'Post', class: 'btn btn-primary' %>
            <% end %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class='user-groups'>
      <% if @profile.user.groups.present? %>
        <h3><span class='user-detail'><%= @profile.user_name %></span> is currently a member of these groups:</h3>
        <% @profile.user.enrollments.each do |enrollment|%>
          
            <%= link_to group_path(enrollment.group) do %>
            <div class='user-group-div'>
              <% if enrollment.group.image.present? %>
                <%= image_tag enrollment.group.image, class: 'profile-group-image' %>
              <% else %>
                <%= image_tag 'profile_image_placeholder.png', class: 'profile-group-image' %>
              <% end %>
              <div class= 'profile-group-details col-xs-9'>
                <h3 class='profile-group-name'><%= enrollment.group.name %></h3>
                <p>is working on...</p>
                <h3 class='profile-group-course'><%= enrollment.group.course %></h3>
                <p><%= enrollment.group.description %></p>
              </div>
            </div>              
            <% end %>

        <% end %>
      <% else %>
        <h3><span class='user-detail'><%= @profile.user_name %></span> is currently not a member of any groups</h3>

      <% end %>

    </div>
    <br/>
    <% if current_user == @profile.user %>
      <%= link_to 'Edit Profile', edit_profile_path(current_user), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>