config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#landing_page'
  resources :suggestions, only: [:create]
  resources :profiles, only: [:edit, :show, :update, :index]
  resources :join_requests, only: [:destroy] do
    delete '/enroll', to: 'join_requests#enroll'
  end
  namespace :member do
    resources :groups, only: [:show, :index] do
      resources :messages, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :enrollments, only: [:destroy]
  resources :groups do
    resources :enrollments, only: [:create]
    resources :join_requests, only: [:create]
  end
  resources :user_messages, only: [:index]
  resources :users do
    resources :user_messages, only: [:new, :create, :destroy]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :enrollments, dependent: :destroy
  has_many :members, through: :enrollments, source: :user
  has_many :join_requests, foreign_key: 'group_id', dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :commitment_hours, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :course, presence: true, length: { minimum: 3 }
  validates :country, presence: true
  validates :time_zone, presence: true
  validates :description, presence: true, length: { minimum: 3 }

  def country_name
    country_fullname = ISO3166::Country[country]

    return '' unless country_fullname.present?

    country_fullname.translations[I18n.locale.to_s] || country_fullname.name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_authorized_for_action, only: [:edit, :update, :destroy]
  def index
    @groups = Group.paginate(page: params[:page], per_page: 6).order('row_order DESC')
  end

  def show
    if current_group.time_zone.present?
      timezone = ActiveSupport::TimeZone[current_group.time_zone]
      @offset = timezone.formatted_offset if timezone.present?
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)

    return render :new, status: :unprocessible_entity unless @group.valid?

    @group.enrollments.create(user_id: current_user.id)
    redirect_to groups_path
  end

  def edit
  end

  def update
    group_updated = current_group.update_attributes(group_params)

    return render :edit, status: :unprocessible_entity unless group_updated

    redirect_to group_path(current_group)
  end

  def destroy
    current_group.destroy

    redirect_to groups_path
  end

  private

  helper_method :current_group
  def current_group
    @group ||= Group.find(params[:id])
  end

  def require_authorized_for_action
    return render_not_found(:unauthorized) if current_group.user != current_user
  end

  def group_params
    params.require(:group).permit(:name, :course, :country, :time_zone, :remote, :commitment_hours, :image, :description)
  end
end

app/controllers/member/groups_controller.rb
module Member
  class GroupsController < ApplicationController
    before_action :authenticate_user!
    def index
      @groups = current_user.enrolled_groups.paginate(page: params[:page], per_page: 6).order('row_order DESC')
    end

    def show
      return render_not_found(:unauthorized) unless current_group.members.find_by_id(current_user.id).present?
      @message = Message.new
      @messages = current_group.messages.paginate(page: params[:page], per_page: 4).order('created_at DESC')
      if current_group.time_zone.present?
        timezone = ActiveSupport::TimeZone[current_group.time_zone]
        @offset = timezone.formatted_offset if timezone.present?
      end
    end

    private

    helper_method :current_group
    def current_group
      @group ||= Group.find(params[:id])
    end
  end
end

app/controllers/member/messages_controller.rb
module Member
  class MessagesController < ApplicationController
    before_action :authenticate_user!
    def new
      group = Group.find(params[:group_id])
      return render_not_found(:unauthorized) unless group.members.find_by_id(current_user.id).present?
      @message = group.messages.new
    end

    def edit
      group = Group.find(params[:group_id])
      @message = group.messages.find(params[:id])
      return render_not_found(:unauthorized) unless @message.user == current_user
    end

    def create
      group = Group.find(params[:group_id])
      return render_not_found(:unauthorized) unless group.members.find_by_id(current_user.id).present?
      group.messages.create(message_params.merge(user_id: current_user.id))
      redirect_to member_group_path(group)
    end

    def update
      group = Group.find(params[:group_id])
      message = group.messages.find(params[:id])
      return render_not_found(:unauthorized) unless message.user == current_user
      message.update_attributes(message_params)
      redirect_to group_path(group)
    end

    def destroy
      group = Group.find(params[:group_id])
      message = group.messages.find(params[:id])
      return render_not_found(:unauthorized) unless message.user == current_user
      message.destroy
      redirect_to group_path(group)
    end

    private

    def message_params
      params.require(:message).permit(:message_title, :message_description)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_member(member)
    link_to profile_path(member), class: 'group-members-profile-link' do
      if member.profile.avatar.present?
        image_tag(member.profile.avatar, class: 'group-members-image')
      else
        image_tag('http://placehold.it/30x30', class: 'group-members-image')
      end
    end
  end

  def render_join_request_button
    if current_user.present? && current_group.members.find_by_id(current_user.id).nil? && current_group.join_requests.find_by('requestor_id = ?', current_user.id).nil?
      return content_tag(:button, 'Join Group', class: 'btn btn-success join-button', data: { toggle: 'modal', target: '#joinRequestModal' })
    end

    if current_user.present? && current_group.join_requests.find_by('requestor_id = ?', current_user.id).present?
      return link_to('Withdraw Join Request', join_request_path(current_group.join_requests.find_by('requestor_id = ?', current_user.id)), method: :delete, class: 'btn btn-danger')
    end
  end

  def render_group_request(request)
    content_tag :div, class: 'individual-group-request' do
      concat(render_group_request_details(request))
      if current_group.user == current_user
        concat(render_group_request_buttons(request))
      end
    end
  end

  private

  def render_group_request_details(request)
    content_tag :div, class: 'group-request-details' do
      content_tag(:h4, link_to(request.requestor.profile.user_name, profile_path(request.requestor), class: 'requestor-profile-link') + ' ' + 'would like to join the group') +
        content_tag(:p, request.message)
    end
  end

  def render_group_request_buttons(request)
    content_tag :div, class: 'group-request-buttons' do
      link_to('Enroll User', join_request_enroll_path(request), method: :delete, class: 'btn btn-success') +
        link_to('Reject Request', join_request_path(request), method: :delete, class: 'btn btn-danger')
    end
  end
end

app/helpers/member/groups_helper.rb
module Member
  module GroupsHelper
  end
end

app/helpers/member/messages_helper.rb
module Member
  module MessagesHelper
  end
end

app/views/member/groups/index.html.erb
<div class='col-xs-12 col-sm-10 col-sm-offset-1'>
  <div class='groups-index-contents-inner'>
    <% @groups.each do |group| %>
      <div class='group-box'>
        <div class='group-front'>
          <%= link_to member_group_path(group), class: 'group-box-link' do %>
            <% if group.image.present? %>
              <%= image_tag(group.image, class: 'group-image')%>
            <% else %>
              <%= image_tag('coverimage.jpg', class: 'group-image') %>
            <% end %>
          <% end %>
        <div class='group-contents'>
          <%= link_to member_group_path(group), class: 'group-box-link' do %>  
            <div class='group-heading'>
              <h1><%= group.name %></h1>
              <p>is working on..</p>
              <h3><%= group.course %></h3>
            </div>
          <% end %>
        <div class='group-details'>
          <div class='group-members'>
            Members: 
            <% group.members.each do |member| %>
              <%= link_to profile_path(member), class: 'group-members-profile-link' do %>
                <% if member.profile.avatar.present? %>
                  <%= image_tag(member.profile.avatar, class: 'group-members-image') %>
                <% else %>
                  <%= image_tag('http://placehold.it/30x30', class: 'group-members-image')%>
                <% end %>      
              <% end %>
            <% end %>
          </div>
          <br/>
          <%= link_to member_group_path(group), class: 'group-box-link' do %>
            <p class='group-description'><%= group.description%></p>
          <% end %>
        </div>            
      </div>
    </div>

        <div class='group-back hidden'>
          <div class='group-contents'>
            <%= link_to member_group_path(group), class: 'group-box-link' do %>
              <div class='group-heading'>
                <h1><%= group.name %></h1>
                <p>is working on..</p>
                <h3><%= group.course %></h3>
              </div>
            <% end %>
            <%= link_to member_group_path(group), class: 'group-box-link' do %>
              <div class='group-prereq'>
                <p>Country: <%= group.country_name %></p>
                <p>Time Zone: <%= group.time_zone %></p>
                <p>Commitment per week: <%= group.commitment_hours%>hrs</p>
                <p>
                  <% if group.remote == true %>
                    Remote members welcome
                  <% else %>
                    Local members only
                  <% end %>
                </p>
              </div>                        
            <% end %>
            <div class='group-details'>
              <br/>
              <div class='group-members'>
                Members: 
                <% group.members.each do |member| %>
                  <%= link_to profile_path(member), class: 'group-members-profile-link' do %>
                    <% if member.profile.avatar.present? %>
                      <%= image_tag(member.profile.avatar, class: 'group-members-image') %>
                    <% else %>
                      <%= image_tag('http://placehold.it/30x30', class: 'group-members-image')%>
                    <% end %>      
                  <% end %>
                <% end %>
              </div>
              <br/>
              <%= link_to member_group_path(group), class: 'group-box-link' do %>
                <p class='group-description'><%= group.description%></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class='pagination-div'>
    <%= will_paginate @groups %>
  </div>      
</div>

app/views/member/groups/show.html.erb
<%= javascript_include_tag 'truncate_message' %>

<div class='col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12'>
  <div class='member-group-contents'>
    <div class='member-group-details'>
      <div class='member-group-details-and-members'>
        <h1 class='member-group-name'><%= current_group.name %></h1>
        <h3>Group Details</h3>
        <br/>
        <p class='member-group-course'>Course: <span class='member-group-coursename'><%= current_group.course %></span></p>
        <p>Commitment per week: <%= current_group.commitment_hours %> hours</p>
        <p>Country: <%= current_group.country_name %></p>
        <p>Time Zone: (GMT <%= @offset %>) <%= current_group.time_zone %> </p>
        <% if current_group.remote.present? %>
          <p>We work remotely!</p>
        <% else %>
          <p>We meet up!</p>
        <% end %>

        <div class='group-members'>
          Members: 
          <% current_group.members.each do |member| %>
            <%= render_member(member) %>
          <% end %>
        </div>
      </div>
        <%= link_to 'Public Group Page', group_path(current_group) , class: 'btn btn-primary' %>
    </div>    

    </br class='clear'>
    <h2>Messages</h2>
    </br>
    <div class='member-group-messages'>      
      <% @messages.each do |message| %>
        <div class='member-message'>
          <h4 class='member-message_title'><%= message.message_title%> - <span class='member-message_time'><%= message.created_at.to_time.strftime('%H:%M %B %e %Y')%></span></h4>
          <div class='member-message_content' data-id=<%= message.id %>>
            <div class='member-message_content_wrapper'>
              <%= message.message_description.html_safe %>
            </div>
            <div class='member-message_content-inner'></div>
          </div>
          <p class='member-message_poster'>-<%= link_to message.user.profile.user_name, profile_path(message.user) %></p>
          </br class='clear'>
        </div>
      <% end %>
    </div>
    <div class='pagination-div'>
      <%= will_paginate @messages %>
    </div>      

    <div class='member-options'>      
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createMessageModal">
        Post Message to Group
      </button>
      <% enrollment = Enrollment.where(user_id: current_user.id, group_id: current_group.id).first %>
      <%= link_to 'Leave Group', enrollment_path(enrollment), method: :delete, data: {confirm: 'Are you sure you want to leave the group?'} ,class: 'btn btn-danger' %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="createMessageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New Message</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for @message, url: member_group_messages_path(current_group), method: :post do |f| %>
              <%= f.input :message_title %>
              <%= f.input :message_description, as: :ckeditor, input_html: { ckeditor: {toolbar: 'projects'}} %>  
          </div>
          <div class="modal-footer">            
              <%= f.submit 'Post', class: 'btn btn-primary' %>
            <% end %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <% @messages.each do |message| %>
      <!-- Modal -->
      <div class="modal fade" id="messageModal-<%= message.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel"><%= message.message_title %></h4>
            </div>
            <div class="modal-body">
              <%= message.message_description.html_safe %>  
            </div>
            <div class="modal-footer">            
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>