config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#landing_page'
  resources :suggestions, only: [:create]
  resources :profiles, only: [:edit, :show, :update, :index]
  resources :join_requests, only: [:destroy] do
    delete '/enroll', to: 'join_requests#enroll'
  end
  namespace :member do
    resources :groups, only: [:show, :index] do
      resources :messages, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :enrollments, only: [:destroy]
  resources :groups do
    resources :enrollments, only: [:create]
    resources :join_requests, only: [:create]
  end
  resources :user_messages, only: [:index]
  resources :users do
    resources :user_messages, only: [:new, :create, :destroy]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :enrollments, dependent: :destroy
  has_many :members, through: :enrollments, source: :user
  has_many :join_requests, foreign_key: 'group_id', dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :commitment_hours, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :course, presence: true, length: { minimum: 3 }
  validates :country, presence: true
  validates :time_zone, presence: true
  validates :description, presence: true, length: { minimum: 3 }

  def country_name
    country_fullname = ISO3166::Country[country]

    return '' unless country_fullname.present?

    country_fullname.translations[I18n.locale.to_s] || country_fullname.name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_authorized_for_action, only: [:edit, :update, :destroy]
  def index
    @groups = Group.paginate(page: params[:page], per_page: 6).order('row_order DESC')
  end

  def show
    if current_group.time_zone.present?
      timezone = ActiveSupport::TimeZone[current_group.time_zone]
      @offset = timezone.formatted_offset if timezone.present?
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.create(group_params)

    return render :new, status: :unprocessible_entity unless @group.valid?

    @group.enrollments.create(user_id: current_user.id)
    redirect_to groups_path
  end

  def edit
  end

  def update
    group_updated = current_group.update_attributes(group_params)

    return render :edit, status: :unprocessible_entity unless group_updated

    redirect_to group_path(current_group)
  end

  def destroy
    current_group.destroy

    redirect_to groups_path
  end

  private

  helper_method :current_group
  def current_group
    @group ||= Group.find(params[:id])
  end

  def require_authorized_for_action
    return render_not_found(:unauthorized) if current_group.user != current_user
  end

  def group_params
    params.require(:group).permit(:name, :course, :country, :time_zone, :remote, :commitment_hours, :image, :description)
  end
end

app/controllers/member/groups_controller.rb
module Member
  class GroupsController < ApplicationController
    before_action :authenticate_user!
    def index
      @groups = current_user.enrolled_groups.paginate(page: params[:page], per_page: 6).order('row_order DESC')
    end

    def show
      return render_not_found(:unauthorized) unless current_group.members.find_by_id(current_user.id).present?
      @message = Message.new
      @messages = current_group.messages.paginate(page: params[:page], per_page: 4).order('created_at DESC')
      if current_group.time_zone.present?
        timezone = ActiveSupport::TimeZone[current_group.time_zone]
        @offset = timezone.formatted_offset if timezone.present?
      end
    end

    private

    helper_method :current_group
    def current_group
      @group ||= Group.find(params[:id])
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_member(member)
    link_to profile_path(member), class: 'group-members-profile-link' do
      if member.profile.avatar.present?
        image_tag(member.profile.avatar, class: 'group-members-image')
      else
        image_tag('http://placehold.it/30x30', class: 'group-members-image')
      end
    end
  end

  def render_join_request_button
    if current_user.present? && current_group.members.find_by_id(current_user.id).nil? && current_group.join_requests.find_by('requestor_id = ?', current_user.id).nil?
      return content_tag(:button, 'Join Group', class: 'btn btn-success join-button', data: { toggle: 'modal', target: '#joinRequestModal' })
    end

    if current_user.present? && current_group.join_requests.find_by('requestor_id = ?', current_user.id).present?
      return link_to('Withdraw Join Request', join_request_path(current_group.join_requests.find_by('requestor_id = ?', current_user.id)), method: :delete, class: 'btn btn-danger')
    end
  end

  def render_group_request(request)
    content_tag :div, class: 'individual-group-request' do
      concat(render_group_request_details(request))
      if current_group.user == current_user
        concat(render_group_request_buttons(request))
      end
    end
  end

  private

  def render_group_request_details(request)
    content_tag :div, class: 'group-request-details' do
      content_tag(:h4, link_to(request.requestor.profile.user_name, profile_path(request.requestor), class: 'requestor-profile-link') + ' ' + 'would like to join the group') +
        content_tag(:p, request.message)
    end
  end

  def render_group_request_buttons(request)
    content_tag :div, class: 'group-request-buttons' do
      link_to('Enroll User', join_request_enroll_path(request), method: :delete, class: 'btn btn-success') +
        link_to('Reject Request', join_request_path(request), method: :delete, class: 'btn btn-danger')
    end
  end
end

app/helpers/member/groups_helper.rb
module Member
  module GroupsHelper
  end
end

app/views/groups/edit.html.erb
<div class='col-xs-10 col-xs-offset-1'>
  <div class='edit-group-contents'>
    <h1>Edit Group Details</h1>
    <%= simple_form_for @group do |f|%>
      <%= f.input :name %>
      <br/>
      <%= f.input :course %>      
      <br/>
      <%= f.input :country, priority: ['United States', 'Australia', 'Singapore'] %>  
      <br/>
      <%= f.input :time_zone, priority: /Australia|US|Singapore/ %>
      <br/>      
      <%= f.input :commitment_hours %>
      <br/>
      <%= f.input :remote %>
      <br/>
      <%= f.input :description %>
      <br/>
      <%= f.input :image %>      
      <br/>

      <%= f.submit 'Apply Changes', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='col-xs-12 col-sm-10 col-sm-offset-1'>
  <div class='groups-index-contents-inner'>
    <% @groups.each do |group| %>
      <div class='group-box'>
        <div class='group-front'>
          <%= link_to group_path(group), class: 'group-box-link' do %>
            <% if group.image.present? %>
              <%= image_tag(group.image, class: 'group-image')%>
            <% else %>
              <%= image_tag('coverimage.jpg', class: 'group-image') %>
            <% end %>
          <% end %>
        <div class='group-contents'>
          <%= link_to group_path(group), class: 'group-box-link' do %>  
            <div class='group-heading'>
              <h1><%= group.name %></h1>
              <p>is working on..</p>
              <h3><%= group.course %></h3>
            </div>
          <% end %>
        <div class='group-details'>
          <div class='group-members'>
            Members: 
            <% group.members.each do |member| %>
              <%= link_to profile_path(member), class: 'group-members-profile-link' do %>
                <% if member.profile.avatar.present? %>
                  <%= image_tag(member.profile.avatar, class: 'group-members-image') %>
                <% else %>
                  <%= image_tag('http://placehold.it/30x30', class: 'group-members-image')%>
                <% end %>      
              <% end %>
            <% end %>
          </div>
          <br/>
          <%= link_to group_path(group), class: 'group-box-link' do %>
            <p class='group-description'><%= group.description%></p>
          <% end %>
        </div>            
      </div>
    </div>

        <div class='group-back hidden'>
          <div class='group-contents'>
            <%= link_to group_path(group), class: 'group-box-link' do %>
              <div class='group-heading'>
                <h1><%= group.name %></h1>
                <p>is working on..</p>
                <h3><%= group.course %></h3>
              </div>
            <% end %>
            <%= link_to group_path(group), class: 'group-box-link' do %>
              <div class='group-prereq'>
                <p>Country: <%= group.country_name %></p>
                <p>Time Zone: <%= group.time_zone %></p>
                <p>Commitment per week: <%= group.commitment_hours%>hrs</p>
                <p>
                  <% if group.remote == true %>
                    Remote members welcome
                  <% else %>
                    Local members only
                  <% end %>
                </p>
              </div>                        
            <% end %>
            <div class='group-details'>
              <br/>
              <div class='group-members'>
                Members: 
                <% group.members.each do |member| %>
                  <%= link_to profile_path(member), class: 'group-members-profile-link' do %>
                    <% if member.profile.avatar.present? %>
                      <%= image_tag(member.profile.avatar, class: 'group-members-image') %>
                    <% else %>
                      <%= image_tag('http://placehold.it/30x30', class: 'group-members-image')%>
                    <% end %>      
                  <% end %>
                <% end %>
              </div>
              <br/>
              <%= link_to group_path(group), class: 'group-box-link' do %>
                <p class='group-description'><%= group.description%></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class='pagination-div'>
    <%= will_paginate @groups %>
  </div>      
</div>

app/views/groups/new.html.erb
<div class='col-xs-10 col-xs-offset-1'>
  <div class='new-group-contents'>
    <h1>Enter Group Details</h1>
    <%= simple_form_for @group do |f|%>
      <%= f.input :name %>
      <br/>
      <%= f.input :course %>      
      <br/>
      <%= f.input :country, priority: ['United States', 'Australia', 'Singapore'] %>  
      <br/>
      <%= f.input :time_zone, priority: /Australia|US|Singapore/ %>
      <br/>
      <%= f.input :commitment_hours %>
      <br/>
      <%= f.input :remote %>
      <br/>
      <%= f.input :description %>
      <br/>
      <%= f.input :image %>      
      <br/>

      <%= f.submit 'Create Group', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12'>
  <div class='current-group-contents'>

    <div class='individual-group-heading'>
      <br/>
      <% if current_group.image.present? %>
        <%= image_tag current_group.image, class: 'group-display-image' %>
      <% else %>
        <%= image_tag 'coverimage.jpg', class: 'group-display-image' %>
      <% end %>
      <br/>
      <br/>
      <div class='individual-group-heading-details-and-buttons'>
        <div class='individual-group-heading-details'>
          <h1><%= current_group.name %></h1>
          <p>is working on...</p>
          <h2><%= current_group.course %></h2>
        </div>
        <% if current_user.present? && current_group.members.find_by_id(current_user.id).present? %>
          <%= link_to 'Member\'s Area', member_group_path(current_group), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>

    <div class='individual-group-details'>
      <h3>Group Details</h3>
      <p>Commitment per week: <%= current_group.commitment_hours %> hours</p>
      <p>Country: <%= current_group.country_name %></p>
      <p>Time Zone: (GMT <%= @offset %>) <%= current_group.time_zone %> </p>
      <% if current_group.remote.present? %>
        <p>Remote learners welcome!</p>
      <% else %>
        <p>Local learners please</p>
      <% end %>

      <div class='group-members'>
        Members: 
        <% current_group.members.each do |member| %>
          <%= render_member(member) %>
        <% end %>
      </div>
    </div>

    <%= link_to profile_path(current_group.user), class: 'group-user-profile-link' do %>
    <div class='individual-group-owner'>
      <%= image_tag current_group.user.profile.avatar, class: 'group-owner-avatar' %>
      <div class='group-owner-details'>
        <h4><%= current_group.user.profile.user_name %></h4>
        <p><%= current_group.user.profile.description %></p>
      </div>
    </div>
    <% end %>

    <div class='individual-group-description'>
      <h3>Group Description</h3>
      <p><%= current_group.description%></p>
    </div>

    <%= render_join_request_button %>

    <!-- Modal -->
    <div class="modal fade" id="joinRequestModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Let the group know more about you</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for JoinRequest.new, url: group_join_requests_path(current_group) do |f| %>
              <%= f.input :message %>
          </div>
          <div class="modal-footer">
            <%= f.submit 'Request to Join', class: 'btn btn-success' %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>            
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <% if current_group.user == current_user %>
      <div class='group-requests'>
        <h3>Group Requests</h3>
        <% current_group.join_requests.each do |request| %>
        <br class='clear'/>
          <%= render_group_request(request) %>
        <% end %>
      </div>

      <br/>
      <%= link_to 'Edit Group Details',edit_group_path(current_group), class: 'btn btn-primary' %>
    <% end %>  
            
  </div>
</div>