config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#landing_page'
  resources :suggestions, only: [:create]
  resources :profiles, only: [:edit, :show, :update, :index]
  resources :join_requests, only: [:destroy] do
    delete '/enroll', to: 'join_requests#enroll'
  end
  namespace :member do
    resources :groups, only: [:show, :index] do
      resources :messages, only: [:new, :create, :edit, :update, :destroy]
    end
  end
  resources :enrollments, only: [:destroy]
  resources :groups do
    resources :enrollments, only: [:create]
    resources :join_requests, only: [:create]
  end
  resources :user_messages, only: [:index]
  resources :users do
    resources :user_messages, only: [:new, :create, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingPals</title>
  <meta name="viewport" content="initial-scale=1">  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'groups_index' %>
  <%= javascript_include_tag 'highlight.pack' %>
  <%= javascript_include_tag 'bootstrap-ckeditor-fix' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700italic,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,600,300' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CodingPals', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'People', profiles_path %></li>
        <li><%= link_to 'Groups', groups_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">        
        <% if current_user.present? %>
          <li><%= link_to 'My Groups', member_groups_path %></li>
          <li><%= link_to 'My Messages', user_messages_path %></li>
          <li><%= link_to 'Add Group', new_group_path %></li>
          <li><%= link_to 'Profile', profile_path(current_user) %></li>
        <% end %>          
        <% if current_user.present? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>          
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
 <% end %>

<section class='page-contents'>
  <%= yield %>
</section>

<footer class="footer">
  <div class="container">
    <p>Brought to you by <%=link_to 'Joshua', 'https://joshuatan.herokuapp.com/'%></p>
  </div>
</footer>

<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>